# * Sales Daily

In [1]:
import configparser
import datetime as dt
import pandas as pd
import numpy as np
import xlrd
import oracledb
import re

config = configparser.ConfigParser()
config.read('../../my_config.ini')
config.sections()

TDMDBPR_user = config['TDMDBPR']['username']
TDMDBPR_pwd = config['TDMDBPR']['password']
TDMDBPR_db = config['TDMDBPR']['db']
TDMDBPR_host = config['TDMDBPR']['host']
TDMDBPR_port = config['TDMDBPR']['port']

AKPIPRD_user = config['AKPIPRD']['username']
AKPIPRD_pwd = config['AKPIPRD']['password']
AKPIPRD_db = config['AKPIPRD']['db']
AKPIPRD_host = config['AKPIPRD']['host']
AKPIPRD_port = config['AKPIPRD']['port']

curr_dt = dt.datetime.now().date()
str_curr_dt = curr_dt.strftime('%Y%m%d')

In [2]:
''' Input parameter '''

op_dir = 'data'
op_sales_file = f'sales_daily_{str_curr_dt}'

# v_year = 0
# v_month_start = 0
# v_month_end = 0
# v_date = 20250101

print(f'\nParameter input...\n')
print(f'   -> op_dir: {op_dir}')
print(f'   -> op_sales_file: {op_sales_file}')
# print(f'\n   -> v_year: {v_year}')
# print(f'   -> v_month_start: {v_month_start}')
# print(f'   -> v_month_end: {v_month_end}')
# print(f'\n   -> v_date: {v_date}')

Parameter input...

   -> op_dir: data
   -> op_sales_file: sales_daily_20260227

## Import Transaction
-> DIM_CORP_KPI

In [3]:
''' Execute transaction '''


# Input parameter
v_start_date = 20250101
print(f'\nParameter input...')
print(f'   -> v_start_date: {v_start_date}')

curr_datetime = dt.datetime.now().strftime('%Y-%m-%d, %H:%M:%S')
print(f'\nData as of {curr_datetime}')


# Connect : TDMDBPR
src_dsn = f'{TDMDBPR_user}/{TDMDBPR_pwd}@{TDMDBPR_host}:{TDMDBPR_port}/{TDMDBPR_db}'
src_conn = oracledb.connect(src_dsn)
src_cur = src_conn.cursor()

query = (f"""
    SELECT /*+PARALLEL(8)*/ 
        TM.TM_KEY_YR, TM.TM_KEY_QTR, TM.TM_KEY_MTH, TM.TM_KEY_WK, A.TM_KEY_DAY
        , A.PRODUCT, A.OWNER_ID, A.METRIC_CD, A.METRIC_NAME, A.COMP_CD, A.VERSION, A.AREA_CD, A.AREA_DESC, A.AREA_TYPE, A.LOAD_DATE, A.REMARK, A.UPD_TM, A.PPN_TM
        , A.METRIC_VALUE AS ACTUAL
        , (TG.METRIC_VALUE / TM.DAYS_IN_MONTH) AS TARGET
        , TG.METRIC_VALUE AS TARGET_MTH
        , TM.DAYS_IN_MONTH, TM.PERIODFLAG
        , O.AREA_NAME, O.AREA_CD_G, O.AREA_NAME_G
        
    FROM CDSAPPO.DIM_CORP_KPI A

    LEFT JOIN GEOSPCAPPO.DIM_TIME_CITRINE TM
        ON TM.TM_KEY_DAY = A.TM_KEY_DAY
        
    LEFT JOIN CDSAPPO.DIM_CORP_TARGET TG
        ON TG.METRIC_CD = A.METRIC_CD
        AND TG.AREA_CD = A.AREA_CD
        AND TG.TM_KEY_DAY = TM.TM_KEY_MTH
        
    LEFT JOIN GEOSPCAPPO.DIM_MOOC_AREA_CITRINE H
        ON H.AREA_TYPE = 'H'
        AND H.AREA_CD = A.AREA_CD
        
    LEFT JOIN (
        SELECT H.AREA_CD, H.AREA_NAME
            , CASE WHEN H.AREA_TYPE = 'H' THEN G.AREA_CD END AREA_CD_G
            , CASE WHEN H.AREA_TYPE = 'H' THEN G.AREA_NAME END AREA_NAME_G
        FROM GEOSPCAPPO.DIM_MOOC_AREA_CITRINE H
        LEFT JOIN (
            SELECT AREA_CD, AREA_NAME
            FROM GEOSPCAPPO.DIM_MOOC_AREA_CITRINE
            WHERE AREA_TYPE = 'G'
        ) G
            ON G.AREA_CD = H.AREA_CD_G
        WHERE AREA_TYPE IN ('P', 'G', 'H')
    ) O
        ON O.AREA_CD = A.AREA_CD
        
    WHERE A.TM_KEY_DAY >= {v_start_date}
    AND REGEXP_LIKE(A.METRIC_CD, 'CS$|CG$') -->> 2025 KPIs
    AND A.AREA_TYPE IN ('P', 'G', 'H')
    AND EXISTS (
        SELECT 1 -->> AREA_CD IN (P, G, H, R, HH, CCAA, CCAATT)
        FROM (
            SELECT DISTINCT ORGID_P AS TMP_CD FROM CDSAPPO.DIM_MOOC_AREA NOLOCK WHERE REMARK <> 'Dummy' AND TEAM_CODE <> 'ไม่ระบุ'
            UNION SELECT DISTINCT ORGID_G AS TMP_CD FROM CDSAPPO.DIM_MOOC_AREA NOLOCK WHERE REMARK <> 'Dummy' AND TEAM_CODE <> 'ไม่ระบุ'
            --UNION SELECT DISTINCT ORGID_R AS TMP_CD FROM CDSAPPO.DIM_MOOC_AREA NOLOCK WHERE REMARK <> 'Dummy' AND TEAM_CODE <> 'ไม่ระบุ'
            UNION SELECT DISTINCT ORGID_H AS TMP_CD FROM CDSAPPO.DIM_MOOC_AREA NOLOCK WHERE REMARK <> 'Dummy' AND TEAM_CODE <> 'ไม่ระบุ'
            --UNION SELECT DISTINCT ORGID_HH AS TMP_CD FROM CDSAPPO.DIM_MOOC_AREA NOLOCK WHERE REMARK <> 'Dummy' AND TEAM_CODE <> 'ไม่ระบุ'
            --UNION SELECT DISTINCT SUBSTR(CCAATT,1,4) AS TMP_CD FROM CDSAPPO.DIM_MOOC_AREA NOLOCK WHERE REMARK <> 'Dummy' AND TEAM_CODE <> 'ไม่ระบุ'
            --UNION SELECT DISTINCT CCAATT AS TMP_CD FROM CDSAPPO.DIM_MOOC_AREA NOLOCK WHERE REMARK <> 'Dummy' AND TEAM_CODE <> 'ไม่ระบุ'
        ) TMP
        WHERE TMP_CD = A.AREA_CD )
""")


try:
    # Create Dataframe
    src_cur.execute(query)
    rows = src_cur.fetchall()
    src_df = pd.DataFrame.from_records(rows, columns=[x[0] for x in src_cur.description])
    print(f'\nDataFrame: {src_df.shape[0]} rows, {src_df.shape[1]} columns')

    # Generate CSV file
    src_df.to_csv(f'{op_dir}/{op_sales_file}.csv', index=False, encoding='utf-8')
    print(f'\n   -> Generate "{op_sales_file}.csv" successfully')

    src_cur.close()


except oracledb.DatabaseError as e:
    print(f'\nError with Oracle : {e}')


finally:
    src_conn.close()

Parameter input...
   -> v_start_date: 20250101

Data as of 2026-02-27, 15:58:31

DataFrame: 2123445 rows, 26 columns

   -> Generate "sales_daily_20260227.csv" successfully

## Import Target
-> DIM_CORP_TARGET

In [4]:
''' Execute transaction '''


# Input parameter
v_target_start_mth = 202601
print(f'\nParameter input...')
print(f'   -> v_target_start_mth: {v_target_start_mth}')

curr_datetime = dt.datetime.now().strftime('%Y-%m-%d, %H:%M:%S')
print(f'\nData as of {curr_datetime}')

# Connect : TDMDBPR
tgt_dsn = f'{TDMDBPR_user}/{TDMDBPR_pwd}@{TDMDBPR_host}:{TDMDBPR_port}/{TDMDBPR_db}'
tgt_conn = oracledb.connect(tgt_dsn)
tgt_cur = tgt_conn.cursor()


try:
    tgt_cur.execute(f"""
        SELECT /*+PARALLEL(8)*/ 
            SUBSTR(TM_KEY_DAY,1,4) AS TM_KEY_YR
            , PRODUCT, METRIC_CD, METRIC_NAME, COMP_CD, AREA_TYPE
            , MAX(LOAD_DATE) LOAD_DATE
            , SUM(CASE WHEN TM_KEY_DAY LIKE '%01' THEN METRIC_VALUE END) M1
            , SUM(CASE WHEN TM_KEY_DAY LIKE '%02' THEN METRIC_VALUE END) M2
            , SUM(CASE WHEN TM_KEY_DAY LIKE '%03' THEN METRIC_VALUE END) M3
            , SUM(CASE WHEN TM_KEY_DAY LIKE '%04' THEN METRIC_VALUE END) M4
            , SUM(CASE WHEN TM_KEY_DAY LIKE '%05' THEN METRIC_VALUE END) M5
            , SUM(CASE WHEN TM_KEY_DAY LIKE '%06' THEN METRIC_VALUE END) M6
            , SUM(CASE WHEN TM_KEY_DAY LIKE '%07' THEN METRIC_VALUE END) M7
            , SUM(CASE WHEN TM_KEY_DAY LIKE '%08' THEN METRIC_VALUE END) M8
            , SUM(CASE WHEN TM_KEY_DAY LIKE '%09' THEN METRIC_VALUE END) M9
            , SUM(CASE WHEN TM_KEY_DAY LIKE '%10' THEN METRIC_VALUE END) M10
            , SUM(CASE WHEN TM_KEY_DAY LIKE '%11' THEN METRIC_VALUE END) M11
            , SUM(CASE WHEN TM_KEY_DAY LIKE '%12' THEN METRIC_VALUE END) M12
        FROM CDSAPPO.DIM_CORP_TARGET
        WHERE TM_KEY_DAY >= {v_target_start_mth}
        AND AREA_TYPE IN ('P', 'G', 'H', 'HH')
        GROUP BY SUBSTR(TM_KEY_DAY,1,4), PRODUCT, METRIC_CD, METRIC_NAME, COMP_CD, AREA_TYPE
        ORDER BY 1, PRODUCT, METRIC_CD, AREA_TYPE
    """)
    rows = tgt_cur.fetchall()
    # print(f'\nCurrent Target Summary...')
    tgt_df = pd.DataFrame.from_records(rows, columns=[x[0] for x in tgt_cur.description])
    
    tgt_cur.close()


except oracledb.DatabaseError as e:
    print(f'\nError with Oracle : {e}')


finally:
    tgt_conn.close()

Parameter input...
   -> v_target_start_mth: 202601

Data as of 2026-02-27, 16:03:46

## Review

In [5]:
''' Target Summary '''

tmp_tgt_df = tgt_df.copy()

# Drop columns that are entirely NaN
tmp_tgt_df = tmp_tgt_df.dropna(axis=1, how='all')

# Create a new column 'diff' by subtracting the 2nd to last from the last
tmp_tgt_df['difference'] = tmp_tgt_df.iloc[:, -1] - tmp_tgt_df.iloc[:, -2]

# mod_col_list = tmp_tgt_df.iloc[:, 7:].columns.tolist()
mod_col_list = tmp_tgt_df.iloc[:, -3:].columns.tolist()
# mod_col_list

for col in mod_col_list:
    tmp_tgt_df[col] = tmp_tgt_df[col].apply(lambda x: format(x, ',.0f'))
    
# tmp_tgt_df

In [6]:
prepaid_tgt_df = tmp_tgt_df.query(" PRODUCT=='PREPAY' and AREA_TYPE=='P' ").copy()
prepaid_tgt_df.reset_index(drop=True)

,TM_KEY_YR,PRODUCT,METRIC_CD,METRIC_NAME,COMP_CD,AREA_TYPE,LOAD_DATE,M1,M2,difference
0,2026,PREPAY,DB1R000900CG,Prepaid Inflow M1 : DTAC - GEO Channel,DTAC,P,2026-02-27 12:14:45,"142,790,510","137,461,235","-5,329,275"
1,2026,PREPAY,DB1R000900CS,Prepaid Inflow M1 : DTAC,DTAC,P,2026-02-27 12:14:45,"193,372,382","172,691,079","-20,681,303"
2,2026,PREPAY,DB1S000101CG,Prepaid Gross Adds : DTAC - GEO Channel,DTAC,P,2026-02-27 12:14:45,"593,432","518,222","-75,210"
3,2026,PREPAY,DB1S000101CS,Prepaid Gross Adds : DTAC,DTAC,P,2026-02-27 12:14:45,"880,158","718,008","-162,150"
4,2026,PREPAY,TB1R000900CG,Prepaid Inflow M1 : TMH - GEO Channel,TRUE,P,2026-02-27 12:14:37,"200,176,724","180,677,788","-19,498,936"
5,2026,PREPAY,TB1R000900CS,Prepaid Inflow M1 : TMH,TRUE,P,2026-02-27 12:14:37,"258,764,607","235,629,548","-23,135,059"
6,2026,PREPAY,TB1S000101CG,Prepaid Gross Adds : TMH - GEO Channel,TRUE,P,2026-02-27 12:14:37,"800,504","724,892","-75,611"
7,2026,PREPAY,TB1S000101CS,Prepaid Gross Adds : TMH,TRUE,P,2026-02-27 12:14:37,"1,080,109","984,576","-95,533"

In [7]:
postpaid_tgt_df = tmp_tgt_df.query(" PRODUCT=='POSTPAID' and AREA_TYPE=='P' ").copy()
postpaid_tgt_df.reset_index(drop=True)

,TM_KEY_YR,PRODUCT,METRIC_CD,METRIC_NAME,COMP_CD,AREA_TYPE,LOAD_DATE,M1,M2,difference
0,2026,POSTPAID,DB2R010500CG,Postpaid Inflow M1 B2C : DTAC - GEO Channel,DTAC,P,2026-02-27 12:14:45,"8,303,901","9,505,388","1,201,487"
1,2026,POSTPAID,DB2R010500CS,Postpaid Inflow M1 B2C : DTAC,DTAC,P,2026-02-27 12:14:45,"16,650,311","17,201,336","551,025"
2,2026,POSTPAID,DB2S010100CG,Postpaid Gross Adds B2C : DTAC - GEO Channel,DTAC,P,2026-02-27 12:14:45,"15,212","15,889",677
3,2026,POSTPAID,DB2S010100CS,Postpaid Gross Adds B2C : DTAC,DTAC,P,2026-02-27 12:14:45,"38,691","37,571","-1,120"
4,2026,POSTPAID,TB2R010500CG,Postpaid Inflow M1 B2C : TMH - GEO Channel,TRUE,P,2026-02-27 12:14:37,"34,824,088","31,215,246","-3,608,842"
5,2026,POSTPAID,TB2R010500CS,Postpaid Inflow M1 B2C : TMH,TRUE,P,2026-02-27 12:14:37,"67,202,669","61,034,116","-6,168,553"
6,2026,POSTPAID,TB2R020500CG,Postpaid Inflow M1 B2B : TMH - GEO Channel,TRUE,P,2026-02-27 12:14:37,"2,239,488","2,238,420","-1,068"
7,2026,POSTPAID,TB2R020500CS,Postpaid Inflow M1 B2B : TMH,TRUE,P,2026-02-27 12:14:37,"2,249,922","2,247,926","-1,996"
8,2026,POSTPAID,TB2S010100CG,Postpaid Gross Adds B2C : TMH - GEO Channel,TRUE,P,2026-02-27 12:14:37,"64,527","59,151","-5,376"
9,2026,POSTPAID,TB2S010100CS,Postpaid Gross Adds B2C : TMH,TRUE,P,2026-02-27 12:14:37,"133,892","123,741","-10,151"
10,2026,POSTPAID,TB2S020100CG,Postpaid Gross Adds B2B : TMH - GEO Channel,TRUE,P,2026-02-27 12:14:37,"3,433","3,436",3
11,2026,POSTPAID,TB2S020100CS,Postpaid Gross Adds B2B : TMH,TRUE,P,2026-02-27 12:14:37,"3,451","3,449",-2

In [8]:
tol_tgt_df = tmp_tgt_df.query(" PRODUCT=='TOL' and AREA_TYPE=='P' ").copy()
tol_tgt_df.reset_index(drop=True)

,TM_KEY_YR,PRODUCT,METRIC_CD,METRIC_NAME,COMP_CD,AREA_TYPE,LOAD_DATE,M1,M2,difference
0,2026,TOL,TB3R000601CG,TOL Inflow M1 Connected : Consumer - GEO Channel,TRUE,P,2026-02-27 12:14:37,"24,588,491","24,427,727","-160,764"
1,2026,TOL,TB3R000601CS,TOL Inflow M1 Connected : Consumer,TRUE,P,2026-02-27 12:14:37,"29,920,091","29,502,219","-417,872"
2,2026,TOL,TB3S000102CG,TOL Gross Adds Connected : Consumer - GEO Channel,TRUE,P,2026-02-27 12:14:37,"44,277","44,050",-227
3,2026,TOL,TB3S000102CS,TOL Gross Adds Connected : Consumer,TRUE,P,2026-02-27 12:14:37,"54,609","53,884",-725

In [9]:
tvs_tgt_df = tmp_tgt_df.query(" PRODUCT=='TVS' and AREA_TYPE=='P' ").copy()
tvs_tgt_df.reset_index(drop=True)

,TM_KEY_YR,PRODUCT,METRIC_CD,METRIC_NAME,COMP_CD,AREA_TYPE,LOAD_DATE,M1,M2,difference
0,2026,TVS,TB4R001004CG,TVS CMDU Inflow M1 - GEO Channel,TRUE,P,2026-02-27 12:14:38,"500,192","500,000",-191
1,2026,TVS,TB4R001004CS,TVS CMDU Inflow M1,TRUE,P,2026-02-27 12:14:38,"500,192","500,000",-191
2,2026,TVS,TB4R001700CG,TVS Now Inflow M1 - GEO Channel,TRUE,P,2026-02-27 12:14:38,"1,498,930","1,647,640","148,710"
3,2026,TVS,TB4R001700CS,TVS Now Inflow M1,TRUE,P,2026-02-27 12:14:38,"2,502,245","2,650,955","148,710"
4,2026,TVS,TB4S001004CG,TVS CMDU Gross Adds - GEO Channel,TRUE,P,2026-02-27 12:14:38,"5,999","6,599",600
5,2026,TVS,TB4S001004CS,TVS CMDU Gross Adds,TRUE,P,2026-02-27 12:14:38,"10,012","10,612",600
6,2026,TVS,TB4S001400CG,TVS Now Gross Adds - GEO Channel,TRUE,P,2026-02-27 12:14:38,"5,999","6,599",600
7,2026,TVS,TB4S001400CS,TVS Now Gross Adds,TRUE,P,2026-02-27 12:14:38,"10,012","10,612",600