# * VINSIGHT : Data Monitoring

## Parameter

In [11]:
import configparser
import datetime as dt
import pandas as pd
import numpy as np
import xlrd
import oracledb
import re
import FN_Monitoring as fn

config = configparser.ConfigParser()
config.read('../../my_config.ini')
config.sections()

TDMDBPR_user = config['TDMDBPR']['username']
TDMDBPR_pwd = config['TDMDBPR']['password']
TDMDBPR_db = config['TDMDBPR']['db']
TDMDBPR_host = config['TDMDBPR']['host']
TDMDBPR_port = config['TDMDBPR']['port']

AKPIPRD_user = config['AKPIPRD']['username']
AKPIPRD_pwd = config['AKPIPRD']['password']
AKPIPRD_db = config['AKPIPRD']['db']
AKPIPRD_host = config['AKPIPRD']['host']
AKPIPRD_port = config['AKPIPRD']['port']

curr_dt = dt.datetime.now().date()
str_curr_dt = curr_dt.strftime('%Y%m%d')

In [12]:
# ''' Input parameter '''

# op_dir = 'data'
# op_monthly_file = f'vis_monthly_{str_curr_dt}'
# op_daily_file = f'vis_daily_{str_curr_dt}'
# op_ccaa_ccaatt_file = f'vis_ccaa_ccaatt_{str_curr_dt}'

# v_year = 0
# v_month_start = 0
# v_month_end = 0
# v_date = 20240101

# # print(f"\nParameter input...\n\n   -> op_dir: {op_dir}\n   -> op_monthly_file: {op_monthly_file}\n   -> op_daily_file: {op_daily_file}")
# print(f'\nParameter input...\n')
# print(f'   -> op_dir: {op_dir}')
# print(f'   -> op_monthly_file: {op_monthly_file}')
# print(f'   -> op_daily_file: {op_daily_file}')
# print(f'   -> op_ccaa_ccaatt_file: {op_ccaa_ccaatt_file}')
# print(f'\n   -> v_year: {v_year}')
# print(f'   -> v_month_start: {v_month_start}')
# print(f'   -> v_month_end: {v_month_end}')
# print(f'   -> v_date: {v_date}')

## Aggregate : Timestamp

### Day-1

In [13]:
''' Execute : AGG_PERF_NEWCO (Day-1) '''


# Input parameter
v_start_date = 20260201
print(f'\nParameter input...')
print(f'   -> v_start_date: {v_start_date}')

curr_datetime = dt.datetime.now().strftime('%Y-%m-%d, %H:%M:%S')
print(f'\nData as of {curr_datetime}')


# Connect : TDMDBPR
src_dsn = f'{TDMDBPR_user}/{TDMDBPR_pwd}@{TDMDBPR_host}:{TDMDBPR_port}/{TDMDBPR_db}'
src_conn = oracledb.connect(src_dsn)
src_cur = src_conn.cursor()
query = (f"""
    SELECT /*+PARALLEL(8)*/
        METRIC_CD, METRIC_NAME, COMP_CD
        , MAX(CASE WHEN AREA_TYPE = 'P' THEN ACTUAL_AS_OF END) AS ACTUAL_AS_OF_P
        , MAX(CASE WHEN AREA_TYPE = 'G' THEN ACTUAL_AS_OF END) AS G
        , MAX(CASE WHEN AREA_TYPE = 'H' THEN ACTUAL_AS_OF END) AS H
        , MAX(CASE WHEN AREA_TYPE = 'HH' THEN ACTUAL_AS_OF END) AS HH
        , MAX(PPN_TM) PPN_TM
    FROM GEOSPCAPPO.AGG_PERF_NEWCO
    WHERE METRIC_CD IN (
        'DB1R000101' --Prepaid Revenue : DTAC (D-1)
        , 'TB1R000101' --Prepaid Revenue : TMH (D-1)
        , 'DB1S000101CG' --Prepaid Gross Adds : DTAC - GEO Channel
        , 'DB1S000101CS' --Prepaid Gross Adds : DTAC
        , 'TB1S000101CG' --Prepaid Gross Adds : TMH - GEO Channel
        , 'TB1S000101CS' --Prepaid Gross Adds : TMH
        , 'DB1R000900CG' --Prepaid Inflow M1 : DTAC - GEO Channel
        , 'DB1R000900CS' --Prepaid Inflow M1 : DTAC
        , 'TB1R000900CG' --Prepaid Inflow M1 : TMH - GEO Channel
        , 'TB1R000900CS' --Prepaid Inflow M1 : TMH
        , 'DB1S000200' --Prepaid Churn Subs : DTAC
        , 'TB1S000200' --Prepaid Churn Subs : TMH
        , 'DB1S000401' --Prepaid Net Adds : DTAC
        , 'TB1S000401' --Prepaid Net Adds : TMH
        )
    AND AREA_TYPE IN ('P', 'G', 'H', 'HH')
    AND TM_KEY_DAY >= {v_start_date} 
    GROUP BY COMP_CD, METRIC_CD, METRIC_NAME
    ORDER BY COMP_CD, METRIC_CD
""")


try:
    # Get : Timestamp
    src_cur.execute(query)
    rows = src_cur.fetchall()
    print(f'\nCurrent Timestamp...')
    d1_src_df = pd.DataFrame.from_records(rows, columns=[x[0] for x in src_cur.description])

    # # Display
    # vis_timestamp_df = chk_src_df.copy()
    # print(f'\n{vis_timestamp_df.to_string(max_cols=8)}') #max_rows=1000
    
    src_cur.close()


except oracledb.DatabaseError as e:
    print(f'\nError with Oracle : {e}')


finally:
    src_conn.close()

Parameter input...
   -> v_start_date: 20260201

Data as of 2026-03-09, 14:10:43

Current Timestamp...

In [14]:
''' Convert Display '''

vis_d1_df = d1_src_df.copy()
cols_to_convert = ['ACTUAL_AS_OF_P', 'G', 'H', 'HH']
vis_d1_df[cols_to_convert] = vis_d1_df[cols_to_convert].astype('Int64')
# vis_d1_df

In [15]:
''' Revenue '''

# d1_rev_df = vis_d1_df.query(" METRIC_CD in ['DB1R000101', 'TB1R000101'] ").reset_index(drop=True)
d1_rev_df = vis_d1_df.query(" METRIC_NAME.str.contains('Revenue') ").reset_index(drop=True)
d1_rev_df

,METRIC_CD,METRIC_NAME,COMP_CD,ACTUAL_AS_OF_P,G,H,HH,PPN_TM
0,DB1R000101,Prepaid Revenue : DTAC (D-1),DTAC,20260307,20260307,20260307,20260307,2026-03-09 07:48:14
1,TB1R000101,Prepaid Revenue : TMH (D-1),TRUE,20260307,20260307,20260307,20260307,2026-03-09 07:48:14

In [16]:
''' Gross Adds, Inflow M1 '''

suffixes = ('CG', 'CS')
d1_sale_df = vis_d1_df.query(" METRIC_CD.str.endswith(@suffixes) ").reset_index(drop=True)
d1_sale_df

,METRIC_CD,METRIC_NAME,COMP_CD,ACTUAL_AS_OF_P,G,H,HH,PPN_TM
0,DB1R000900CG,Prepaid Inflow M1 : DTAC - GEO Channel,DTAC,20260308,20260308,20260308,20260308,2026-03-09 09:05:55
1,DB1R000900CS,Prepaid Inflow M1 : DTAC,DTAC,20260308,<NA>,<NA>,<NA>,2026-03-09 09:05:55
2,DB1S000101CG,Prepaid Gross Adds : DTAC - GEO Channel,DTAC,20260308,20260308,20260308,20260308,2026-03-09 09:05:55
3,DB1S000101CS,Prepaid Gross Adds : DTAC,DTAC,20260308,<NA>,<NA>,<NA>,2026-03-09 09:05:55
4,TB1R000900CG,Prepaid Inflow M1 : TMH - GEO Channel,TRUE,20260308,20260308,20260308,20260308,2026-03-09 09:05:55
5,TB1R000900CS,Prepaid Inflow M1 : TMH,TRUE,20260308,<NA>,<NA>,<NA>,2026-03-09 09:05:55
6,TB1S000101CG,Prepaid Gross Adds : TMH - GEO Channel,TRUE,20260308,20260308,20260308,20260308,2026-03-09 09:05:55
7,TB1S000101CS,Prepaid Gross Adds : TMH,TRUE,20260308,<NA>,<NA>,<NA>,2026-03-09 09:05:55

In [17]:
''' Churn, Net Adds '''

d1_sub_df = vis_d1_df.query(" METRIC_NAME.str.contains('Churn|Net Add') ").reset_index(drop=True)
d1_sub_df

,METRIC_CD,METRIC_NAME,COMP_CD,ACTUAL_AS_OF_P,G,H,HH,PPN_TM
0,DB1S000200,Prepaid Churn Subs : DTAC,DTAC,<NA>,<NA>,<NA>,<NA>,2026-03-09 11:07:29
1,DB1S000401,Prepaid Net Adds : DTAC,DTAC,20260306,20260306,20260306,<NA>,2026-03-09 11:07:29
2,TB1S000200,Prepaid Churn Subs : TMH,TRUE,<NA>,<NA>,<NA>,<NA>,2026-03-09 11:07:29
3,TB1S000401,Prepaid Net Adds : TMH,TRUE,20260306,20260306,20260306,20260306,2026-03-09 11:07:29

### Main KPIs (exclude Day-1)

In [18]:
''' Execute : AGG_PERF_NEWCO (Main) '''


# Input parameter
v_start_date = 20260201
print(f'\nParameter input...')
print(f'   -> v_start_date: {v_start_date}')

curr_datetime = dt.datetime.now().strftime('%Y-%m-%d, %H:%M:%S')
print(f'\nData as of {curr_datetime}')


# Connect : TDMDBPR
src_dsn = f'{TDMDBPR_user}/{TDMDBPR_pwd}@{TDMDBPR_host}:{TDMDBPR_port}/{TDMDBPR_db}'
src_conn = oracledb.connect(src_dsn)
src_cur = src_conn.cursor()
query = (f"""
    SELECT /*+PARALLEL(8)*/ PPN_TM, AREA_TYPE
        , COUNT(DISTINCT METRIC_CD) CNT_METRIC, COUNT(1) ROW_CNT
        , MIN(TM_KEY_DAY) MIN_DT, MAX(TM_KEY_DAY) MAX_DT, MAX(ACTUAL_AS_OF) LAST_ACTUAL
    FROM GEOSPCAPPO.AGG_PERF_NEWCO
    WHERE CENTER IN ('Revenue', 'Sales', 'Profitability')
    AND METRIC_CD NOT IN (
        'DB1R000101' --Prepaid Revenue : DTAC (D-1)
        , 'TB1R000101' --Prepaid Revenue : TMH (D-1)
        , 'DB1S000101CG' --Prepaid Gross Adds : DTAC - GEO Channel
        , 'DB1S000101CS' --Prepaid Gross Adds : DTAC
        , 'TB1S000101CG' --Prepaid Gross Adds : TMH - GEO Channel
        , 'TB1S000101CS' --Prepaid Gross Adds : TMH
        , 'DB1R000900CG' --Prepaid Inflow M1 : DTAC - GEO Channel
        , 'DB1R000900CS' --Prepaid Inflow M1 : DTAC
        , 'TB1R000900CG' --Prepaid Inflow M1 : TMH - GEO Channel
        , 'TB1R000900CS' --Prepaid Inflow M1 : TMH
        , 'DB1S000200' --Prepaid Churn Subs : DTAC
        , 'TB1S000200' --Prepaid Churn Subs : TMH
        , 'DB1S000401' --Prepaid Net Adds : DTAC
        , 'TB1S000401' --Prepaid Net Adds : TMH
        )
    AND TM_KEY_DAY >= {v_start_date} 
    GROUP BY PPN_TM, AREA_TYPE
    ORDER BY PPN_TM, AREA_TYPE
""")


try:
    # Get : Timestamp
    src_cur.execute(query)
    rows = src_cur.fetchall()
    print(f'\nCurrent Timestamp...')
    chk_src_df = pd.DataFrame.from_records(rows, columns=[x[0] for x in src_cur.description])

    # Display
    vis_timestamp_df = chk_src_df.copy()
    print(f'\n{vis_timestamp_df.to_string(max_cols=7)}') #max_rows=1000
    
    src_cur.close()


except oracledb.DatabaseError as e:
    print(f'\nError with Oracle : {e}')


finally:
    src_conn.close()

Parameter input...
   -> v_start_date: 20260201

Data as of 2026-03-09, 14:15:05

Current Timestamp...

                PPN_TM AREA_TYPE  CNT_METRIC  ROW_CNT    MIN_DT    MAX_DT  LAST_ACTUAL
0  2026-03-09 02:46:14         H         312   718848  20260201  20260308     20260307
1  2026-03-09 02:52:15         H           4     9216  20260201  20260308     20260308
2  2026-03-09 03:54:58        HH         280   967680  20260201  20260308     20260307
3  2026-03-09 04:00:41        HH           4    13824  20260201  20260308     20260308
4  2026-03-09 11:07:29         C         269     9684  20260201  20260308     20260307
5  2026-03-09 11:07:29         G         423   121824  20260201  20260308     20260307
6  2026-03-09 11:07:29         P         537    19332  20260201  20260308     20260307
7  2026-03-09 11:07:29         Z          29     7308  20260201  20260308     20260306
8  2026-03-09 11:08:26         C           4      144  20260201  20260308     20260308
9  2026-03-09 11:08:26         G           4     1152  20260201  20260308     20260308
10 2026-03-09 11:08:26         P           4      144  20260201  20260308     20260308

In [19]:
# ''' Execute : AGG_PERF_NEWCO_CCAA '''


# # Input parameter
# curr_datetime = dt.datetime.now().strftime('%Y-%m-%d, %H:%M:%S')
# v_start_date = 20260101
# print(f'\nParameter input...\n')
# print(f'   -> Data as of {curr_datetime}')
# print(f'   -> v_start_date: {v_start_date}')


# # Connect : TDMDBPR
# src_dsn = f'{TDMDBPR_user}/{TDMDBPR_pwd}@{TDMDBPR_host}:{TDMDBPR_port}/{TDMDBPR_db}'
# src_conn = oracledb.connect(src_dsn)
# src_cur = src_conn.cursor()
# query = (f"""
#     SELECT /*+PARALLEL(8)*/ AREA_TYPE
#         , MAX(PPN_TM) PPN_TM
#         , COUNT(1) ROW_CNT, MIN(TM_KEY_DAY) MIN_DT, MAX(TM_KEY_DAY) MAX_DT, MAX(ACTUAL_AS_OF) LAST_ACTUAL
#         , COUNT(DISTINCT METRIC_CD) CNT_METRIC
#     FROM GEOSPCAPPO.AGG_PERF_NEWCO_CCAA 
#     WHERE TM_KEY_DAY >= {v_start_date} 
#     GROUP BY AREA_TYPE
#     ORDER BY 1
# """)


# try:
#     # Get : Timestamp
#     src_cur.execute(query)
#     rows = src_cur.fetchall()
#     print(f'\nCurrent Timestamp...')
#     chk_src_df = pd.DataFrame.from_records(rows, columns=[x[0] for x in src_cur.description])

#     # Display
#     vis_timestamp_df = chk_src_df.copy()
#     print(f'\n{vis_timestamp_df.to_string(max_cols=7)}') #max_rows=1000
    
#     src_cur.close()


# except oracledb.DatabaseError as e:
#     print(f'\nError with Oracle : {e}')


# finally:
#     src_conn.close()

In [20]:
# ''' Execute : AGG_PERF_NEWCO_CCAATT '''


# # Input parameter
# curr_datetime = dt.datetime.now().strftime('%Y-%m-%d, %H:%M:%S')
# v_start_date = 20251101
# print(f'\nParameter input...\n')
# print(f'   -> Data as of {curr_datetime}')
# print(f'   -> v_start_date: {v_start_date}')


# # Connect : TDMDBPR
# src_dsn = f'{TDMDBPR_user}/{TDMDBPR_pwd}@{TDMDBPR_host}:{TDMDBPR_port}/{TDMDBPR_db}'
# src_conn = oracledb.connect(src_dsn)
# src_cur = src_conn.cursor()
# query = (f"""
#     SELECT /*+PARALLEL(8)*/ AREA_TYPE
#         , MAX(PPN_TM) PPN_TM
#         , COUNT(1) ROW_CNT, MIN(TM_KEY_DAY) MIN_DT, MAX(TM_KEY_DAY) MAX_DT, MAX(ACTUAL_AS_OF) LAST_ACTUAL
#         , COUNT(DISTINCT METRIC_CD) CNT_METRIC
#     FROM GEOSPCAPPO.AGG_PERF_NEWCO_CCAATT 
#     WHERE TM_KEY_DAY >= {v_start_date} 
#     GROUP BY AREA_TYPE
#     ORDER BY 1
# """)


# try:
#     # Get : Timestamp
#     src_cur.execute(query)
#     rows = src_cur.fetchall()
#     print(f'\nCurrent Timestamp...')
#     chk_src_df = pd.DataFrame.from_records(rows, columns=[x[0] for x in src_cur.description])

#     # Display
#     vis_timestamp_df = chk_src_df.copy()
#     print(f'\n{vis_timestamp_df.to_string(max_cols=7)}') #max_rows=1000
    
#     src_cur.close()


# except oracledb.DatabaseError as e:
#     print(f'\nError with Oracle : {e}')


# finally:
#     src_conn.close()