# * ETL-Actual MKS : Broadband
    (P, Z, G, H, HH, CCAA) level

In [1]:
import configparser
import datetime as dt
import pandas as pd
import numpy as np
import oracledb
import re
import FN_Actual_MKS_Broadband as fn

config = configparser.ConfigParser()
config.read('../../../my_config.ini')
config.sections()

TDMDBPR_user = config['TDMDBPR']['username']
TDMDBPR_pwd = config['TDMDBPR']['password']
TDMDBPR_db = config['TDMDBPR']['db']
TDMDBPR_host = config['TDMDBPR']['host']
TDMDBPR_port = config['TDMDBPR']['port']

AKPIPRD_user = config['AKPIPRD']['username']
AKPIPRD_pwd = config['AKPIPRD']['password']
AKPIPRD_db = config['AKPIPRD']['db']
AKPIPRD_host = config['AKPIPRD']['host']
AKPIPRD_port = config['AKPIPRD']['port']

curr_dt = dt.datetime.now().date()
next_week_dt = curr_dt + dt.timedelta(days=7)
str_curr_dt = curr_dt.strftime('%Y%m%d')
str_next_week_dt = next_week_dt.strftime('%Y%m%d')
yyyymm_curr = curr_dt.strftime('%Y%m')
yyyymm_next_week = next_week_dt.strftime('%Y%m')

## Latest Source Summary

In [8]:
# Connect : TDMDBPR
src_dsn = f'{TDMDBPR_user}/{TDMDBPR_pwd}@{TDMDBPR_host}:{TDMDBPR_port}/{TDMDBPR_db}'
src_conn = oracledb.connect(src_dsn)
src_cur = src_conn.cursor()


try:
    # Get : Actual Summary from "FCT_BB_SHAREV4_ISP_SUBS"
    src_cur.execute("""
        SELECT *
        FROM (
            SELECT TM_KEY_MTH
                , CASE WHEN AREA_TYPE = 'TH' THEN 'P' ELSE AREA_TYPE END AREA_TYPE
                , SUM(COALESCE(TOL,0) + COALESCE(AISBBB,0) + COALESCE(NT,0)) TOTAL
                , SUM(TOL) TOL
                , SUM(AISBBB) AISBBB
                , SUM(NT) NT
                , SUM(BBB) "3BB"
                , SUM(AIS) AIS
            FROM CORPNSBOX.FCT_BB_SHAREV4_ISP_SUBS A
            WHERE TM_KEY_MTH >= 202501
            --AND TM_KEY_MTH <= 202512
            AND VER = 'FINAL'
            AND (AREA_TYPE = 'TH' 
                OR (AREA_TYPE = 'CCAA' AND EXISTS (SELECT 1 FROM CDSAPPO.DIM_MOOC_AREA O WHERE O.TEAM_CODE <> 'ไม่ระบุ' AND O.REMARK <> 'Dummy' AND SUBSTR(O.CCAATT,1,4) = A.AREA_CD)))
            GROUP BY TM_KEY_MTH, AREA_TYPE
        ) TMP
        WHERE TOL > 0 AND AISBBB > 0 AND NT > 0
        AND AREA_TYPE = 'P'
        ORDER BY 1,2
    """)
    rows = src_cur.fetchall()
    print(f'\nCurrent Source Summary...')
    chk_src_df = pd.DataFrame.from_records(rows, columns=[x[0] for x in src_cur.description])

    # Get : MAX(TM_KEY_MTH)
    v_mth_end_src = chk_src_df['TM_KEY_MTH'].max().astype(int)
    print(f'\nv_mth_end_src: {v_mth_end_src}')
    # print(f'\nv_mth_end_src: {v_mth_end_src[0]}')
    
    src_cur.close()


except oracledb.DatabaseError as e:
    print(f'\nError with Oracle : {e}')


finally:
    src_conn.close()

Current Source Summary...

v_mth_end_src: 202607

In [10]:
''' Source Summary '''

tmp_src_df = chk_src_df.copy()
mod_col_list = tmp_src_df.iloc[:, 2:].columns.tolist()
for col in mod_col_list:
    tmp_src_df[col] = tmp_src_df[col].apply(lambda x: format(x, ',.0f'))
# print(f'\n{tmp_src_df}')

tmp_src_df

,TM_KEY_MTH,AREA_TYPE,TOTAL,TOL,AISBBB,NT,3BB,AIS
0,202501,P,"9,975,572","3,141,715","5,033,857","1,800,000","2,013,934","3,019,922"
1,202502,P,"10,036,546","3,149,791","5,086,755","1,800,000","1,936,553","3,150,202"
2,202503,P,"10,014,545","3,162,839","5,051,706","1,800,000","1,911,414","3,140,292"
3,202504,P,"10,029,503","3,168,577","5,060,926","1,800,000","1,917,959","3,142,967"
4,202505,P,"10,061,670","3,175,523","5,086,147","1,800,000","1,905,794","3,180,353"
5,202506,P,"10,100,306","3,179,240","5,121,066","1,800,000","1,946,656","3,174,410"
6,202507,P,"10,127,956","3,180,059","5,147,897","1,800,000","1,962,306","3,185,590"
7,202508,P,"10,093,028","3,184,666","5,108,362","1,800,000","1,929,013","3,179,348"
8,202509,P,"10,118,919","3,191,958","5,126,961","1,800,000","1,924,224","3,202,737"
9,202510,P,"10,137,010","3,204,174","5,132,836","1,800,000","1,898,184","3,234,653"
10,202511,P,"10,171,107","3,213,000","5,158,107","1,800,000","1,787,757","3,370,350"
11,202512,P,"10,265,341","3,226,093","5,239,248","1,800,000","962,803","4,276,445"
12,202601,P,"10,315,469","3,237,440","5,278,029","1,800,000","925,649","4,352,380"
13,202602,P,"10,335,449","3,248,955","5,286,494","1,800,000","917,946","4,368,548"
14,202603,P,"10,358,269","3,263,352","5,294,917","1,800,000","878,448","4,416,469"
15,202604,P,"10,396,044","3,272,920","5,323,124","1,800,000","831,616","4,491,509"
16,202605,P,"10,431,910","3,280,553","5,351,357","1,800,000","825,107","4,526,250"
17,202606,P,"10,466,718","3,291,284","5,375,434","1,800,000","870,612","4,504,823"
18,202607,P,"10,484,070","3,305,671","5,378,399","1,800,000","866,388","4,512,011"

## Latest Fact Summary

In [11]:
# Connect : AKPIPRD
tgt_dsn = f'{AKPIPRD_user}/{AKPIPRD_pwd}@{AKPIPRD_host}:{AKPIPRD_port}/{AKPIPRD_db}'
tgt_conn = oracledb.connect(tgt_dsn)
tgt_cur = tgt_conn.cursor()


try:
    # Get : Actual Summary from "FCT_BROADBAND_MKS"
    tgt_cur.execute("""
        SELECT TM_KEY_MTH, AREA_TYPE 
            , SUM(CASE WHEN METRIC_CD IN ('VIN00081', 'VIN00082', 'VIN00083', 'VIN00084') THEN SUBS_VALUE END) AS TOTAL
            , SUM(CASE WHEN METRIC_CD = 'VIN00081' THEN SUBS_VALUE END) AS TOL
            , SUM(CASE WHEN METRIC_CD = 'VIN00080' THEN SUBS_VALUE END) AS AISBBB
            , SUM(CASE WHEN METRIC_CD = 'VIN00084' THEN SUBS_VALUE END) AS NT
            , SUM(CASE WHEN METRIC_CD = 'VIN00082' THEN SUBS_VALUE END) "3BB"
            , SUM(CASE WHEN METRIC_CD = 'VIN00083' THEN SUBS_VALUE END) AIS
            --, MAX(LOAD_DATE) LOAD_DATE
        FROM AUTOKPI.FCT_BROADBAND_MKS 
        WHERE TM_KEY_MTH >= 202501 --AND TM_KEY_MTH <= 202404
        AND TM_KEY_DAY LIKE '%01'
        AND AREA_TYPE = 'P'
        GROUP BY TM_KEY_MTH, AREA_TYPE 
        ORDER BY 1
    """)
    rows = tgt_cur.fetchall()
    print(f'\nCurrent Fact Summary...')
    chk_tgt_df = pd.DataFrame.from_records(rows, columns=[x[0] for x in tgt_cur.description])

    # Get : MAX(TM_KEY_MTH)
    v_mth_end_fct = chk_tgt_df['TM_KEY_MTH'].max().astype(int)
    print(f'\nv_mth_end_fct: {v_mth_end_fct}')

    # tgt_cur.execute("SELECT MAX(TM_KEY_MTH) FROM AUTOKPI.FCT_BROADBAND_MKS NOLOCK")
    # max_mth_fct = tgt_cur.fetchone()
    # print(f'\nv_max_mth_fct: {max_mth_fct[0]}')
    
    tgt_cur.close()


except oracledb.DatabaseError as e:
    print(f'\nError with Oracle : {e}')


finally:
    tgt_conn.close()

Current Fact Summary...

v_mth_end_fct: 202605

In [13]:
''' Silver Summary '''

tmp_tgt_df = chk_tgt_df.copy()
mod_col_list = tmp_tgt_df.iloc[:, 2:].columns.tolist()
for col in mod_col_list:
    tmp_tgt_df[col] = tmp_tgt_df[col].apply(lambda x: format(x, ',.0f'))
# print(f'\n{tmp_tgt_df}')

tmp_tgt_df

,TM_KEY_MTH,AREA_TYPE,TOTAL,TOL,AISBBB,NT,3BB,AIS
0,202501,P,"9,975,280","3,141,442","5,033,861","1,799,991","2,013,932","3,019,915"
1,202502,P,"10,036,258","3,149,505","5,086,763","1,800,001","1,936,550","3,150,202"
2,202503,P,"10,014,376","3,162,673","5,051,692","1,800,001","1,911,413","3,140,289"
3,202504,P,"10,029,496","3,168,570","5,060,938","1,800,008","1,917,946","3,142,972"
4,202505,P,"10,061,670","3,175,516","5,086,161","1,800,007","1,905,787","3,180,360"
5,202506,P,"10,100,147","3,179,076","5,121,078","1,800,015","1,946,656","3,174,400"
6,202507,P,"10,127,778","3,179,894","5,147,897","1,799,990","1,962,321","3,185,573"
7,202508,P,"10,092,859","3,184,500","5,108,361","1,800,006","1,929,005","3,179,348"
8,202509,P,"10,118,779","3,191,792","5,126,961","1,800,004","1,924,234","3,202,749"
9,202510,P,"10,136,860","3,204,008","5,132,842","1,800,011","1,898,200","3,234,641"
10,202511,P,"10,170,941","3,212,839","5,158,109","1,800,009","1,787,745","3,370,348"
11,202512,P,"10,265,141","3,225,922","5,239,236","1,799,987","962,801","4,276,431"
12,202601,P,"10,315,307","3,237,265","5,278,023","1,800,014","925,636","4,352,392"
13,202602,P,"10,335,269","3,248,786","5,286,490","1,799,999","917,942","4,368,542"
14,202603,P,"10,358,158","3,263,245","5,294,910","1,800,001","878,444","4,416,468"
15,202604,P,"10,395,955","3,272,812","5,323,129","1,800,012","831,617","4,491,514"
16,202605,P,"10,181,812","3,280,443","5,351,346","1,550,000","825,109","4,526,260"

## Check Diff Summary

In [ ]:
# ''' Temp '''

# chk_diff_df = chk_src_df.iloc[-1].compare(chk_tgt_df.iloc[-1])
# chk_diff_df['diff'] = chk_diff_df['self'] - chk_diff_df['other']
# mod_col_list = chk_diff_df.columns.tolist()
# for col in mod_col_list:
#     chk_diff_df[col] = chk_diff_df[col].apply(lambda x: format(x, ',.0f'))

# chk_diff_df

In [14]:
''' Compare Latest Actual '''

latest_src_actual = chk_src_df.loc[chk_src_df['TM_KEY_MTH']==v_mth_end_src]
# latest_src_actual

# latest_fct_actual = chk_tgt_df.loc[chk_tgt_df['TM_KEY_MTH']==v_mth_end_src]
latest_fct_actual = chk_tgt_df.loc[chk_tgt_df['TM_KEY_MTH']==chk_tgt_df['TM_KEY_MTH'].max()]
# latest_fct_actual

chk_diff_latest_actual = latest_src_actual.iloc[-1].compare(latest_fct_actual.iloc[-1])
chk_diff_latest_actual['diff'] = chk_diff_latest_actual['self'] - chk_diff_latest_actual['other']
mod_col_list = chk_diff_latest_actual.columns.tolist()
for col in mod_col_list:
    chk_diff_latest_actual[col] = chk_diff_latest_actual[col].apply(lambda x: format(x, ',.0f'))

chk_diff_latest_actual

                  self       other     diff
TM_KEY_MTH     202,607     202,605        2
TOTAL       10,484,070  10,181,812  302,258
TOL          3,305,671   3,280,443   25,228
AISBBB       5,378,399   5,351,346   27,053
NT           1,800,000   1,550,000  250,000
3BB            866,388     825,109   41,279
AIS          4,512,011   4,526,260  -14,249

## ETL Process...

### DB source to DB Target
    Delete -> Insert

    Source : CORPNSBOX.FCT_BB_SHARE_SUBS_CCAATT
             CDSAPPO.DIM_MOOC_AREA
             CDSAPPO.DIM_TIME
    
    Target : AUTOKPI.FCT_BROADBAND_MKS

### Input Parameter

In [16]:
''' Manual Config '''
# v_update_flag = 'N'
v_target_schema = 'AUTOKPI'
v_target_table = 'FCT_BROADBAND_MKS'
v_sql_update_fact = 'Update-FCT_BROADBAND_MKS.sql'
v_sql_mockup_fact = 'Mock-FCT_BROADBAND_MKS.sql'
v_sql_initial_fact = 'Initial-FCT_BROADBAND_MKS.sql'

''' Auto Config '''
v_update_flag = 'Y' if chk_diff_latest_actual.size > 0 else 'N'
# v_max_mth_fct = max_mth_fct[0]
v_mth_end_fct_year = pd.to_datetime(v_mth_end_fct, format='%Y%m').year
v_mth_end_fct_month = pd.to_datetime(v_mth_end_fct, format='%Y%m').month
# v_prev_mth_fct = v_mth_end_fct-1 if v_mth_end_fct_month != 1 else float(str(v_mth_end_fct_year-1)+str(12))

''' Show Auto Config '''
print(f'\nyyyymm_next_week: {yyyymm_next_week}')
print(f'\nv_update_flag: {v_update_flag}')
print(f'v_mth_end_src: {v_mth_end_src}')
print(f'v_mth_end_fct: {v_mth_end_fct}')
# print(f'v_max_mth_fct: {v_max_mth_fct}')
# print(f'v_prev_mth_fct: {v_prev_mth_fct}')

yyyymm_next_week: 202609

v_update_flag: Y
v_mth_end_src: 202607
v_mth_end_fct: 202605

#### Incremental

In [7]:
# ''' Auto Process '''

# job_start_datetime = dt.datetime.now().strftime('%Y-%m-%d, %H:%M:%S')
# print(f'\nJob Start... {job_start_datetime}')

# # Process flow
# if v_update_flag == 'Y':
#     print(f'\n*** Source update current month Fact ***')
#     fn.src_update_to_fact(v_mth_end_src, v_target_schema, v_target_table, v_sql_update_fact)

# elif v_update_flag == 'N':
#     print(f'\n*** Not update ***')
        
# print(f'\nJob Done !!!')

Job Start... 2026-06-12, 11:54:59

*** Source update current month Fact ***

Param input...

   -> mth_end_src: 202605.0
   -> target_schema: AUTOKPI
   -> target_table: FCT_BROADBAND_MKS
   -> sql_update_fact: Update-FCT_BROADBAND_MKS.sql
   -> v_query_param: {'mth_end_src': 202605.0}

TDMDBPR : Connected

AKPIPRD : Connected

Processing...

Create Dataframe...

   -> src_df : 364250 rows, 17 columns

   -> DELETE : "FCT_BROADBAND_MKS" : Done !

   -> INSERT : "FCT_BROADBAND_MKS" : Done !

TDMDBPR : Disconnected

AKPIPRD : Disconnected

Job Done !!!

#### Initial

In [17]:
''' Initial Process '''

v_initial_mth_start = 202501
v_initial_mth_end = 202607

job_start_datetime = dt.datetime.now().strftime('%Y-%m-%d, %H:%M:%S')
print(f'\nJob Start... {job_start_datetime}')

print(f'\n*** Re-run initial data to Fact ***')
fn.src_initial_to_fact(v_initial_mth_start, v_initial_mth_end, v_target_schema, v_target_table, v_sql_initial_fact)

print(f'\nJob Done !!!')

Job Start... 2026-09-02, 11:34:24

*** Re-run initial data to Fact ***

Param input...

   -> initial_mth_start: 202501
   -> initial_mth_end: 202607
   -> target_schema: AUTOKPI
   -> target_table: FCT_BROADBAND_MKS
   -> sql_initial_fact: Initial-FCT_BROADBAND_MKS.sql
   -> v_query_param: {'initial_mth_start': 202501, 'initial_mth_end': 202607}

TDMDBPR : Connected

AKPIPRD : Connected

Processing...

Create Dataframe...

   -> src_df : 6767040 rows, 17 columns

   -> DELETE : "FCT_BROADBAND_MKS" : Done !

   -> INSERT : "FCT_BROADBAND_MKS" : Done !

TDMDBPR : Disconnected

AKPIPRD : Disconnected

Job Done !!!

## Check Result : "FCT_BROADBAND_MKS"

In [18]:
''' Create Result DataFrame '''

# Connect : AKPIPRD
tgt_dsn = f'{AKPIPRD_user}/{AKPIPRD_pwd}@{AKPIPRD_host}:{AKPIPRD_port}/{AKPIPRD_db}'
tgt_conn = oracledb.connect(tgt_dsn)
tgt_cur = tgt_conn.cursor()


try:
    # Get : Result Data Summary
    tgt_cur.execute("""
        SELECT TM_KEY_MTH, AREA_NO, AREA_TYPE, COALESCE(REMARK, 'Actual') AS REMARK
            -->> Subs
            , SUM(CASE WHEN METRIC_CD IN ('VIN00086', 'VIN00087', 'VIN00088', 'VIN00089') THEN METRIC_VALUE END) AS TOTAL
            , SUM(CASE WHEN METRIC_CD = 'VIN00086' THEN METRIC_VALUE END) AS TOL
            , SUM(CASE WHEN METRIC_CD = 'VIN00085' THEN METRIC_VALUE END) AS "AIS & 3BB"
            , SUM(CASE WHEN METRIC_CD = 'VIN00089' THEN METRIC_VALUE END) AS NT
            , SUM(CASE WHEN METRIC_CD = 'VIN00087' THEN METRIC_VALUE END) AS "3BB"
            , SUM(CASE WHEN METRIC_CD = 'VIN00088' THEN METRIC_VALUE END) AS AIS
            -->> % MKS
            , SUM(CASE WHEN AREA_TYPE = 'P' AND METRIC_CD IN ('VIN00081', 'VIN00082', 'VIN00083', 'VIN00084') THEN METRIC_VALUE END) AS "% TOTAL"
            , SUM(CASE WHEN AREA_TYPE = 'P' AND METRIC_CD = 'VIN00081' THEN METRIC_VALUE END) AS "% TOL"
            , SUM(CASE WHEN AREA_TYPE = 'P' AND METRIC_CD = 'VIN00080' THEN METRIC_VALUE END) AS "% AIS & 3BB"
            , SUM(CASE WHEN AREA_TYPE = 'P' AND METRIC_CD = 'VIN00084' THEN METRIC_VALUE END) AS "% NT"
            , SUM(CASE WHEN AREA_TYPE = 'P' AND METRIC_CD = 'VIN00082' THEN METRIC_VALUE END) AS "% 3BB"
            , SUM(CASE WHEN AREA_TYPE = 'P' AND METRIC_CD = 'VIN00083' THEN METRIC_VALUE END) AS "% AIS"
            -->> Count
            , COUNT(DISTINCT METRIC_CD) AS CNT_METRIC
            , COUNT(DISTINCT AREA_CD) AS CNT_AREA
            , COUNT(1) AS ROW_CNT
            , MAX(LOAD_DATE) AS LOAD_DATE
        FROM AUTOKPI.FCT_BROADBAND_MKS 
        WHERE TM_KEY_DAY >= 20250101
        AND TM_KEY_DAY LIKE '%01'
        GROUP BY TM_KEY_MTH, AREA_NO, AREA_TYPE, REMARK
        --ORDER BY 1,2
    """)
    rows = tgt_cur.fetchall()
    print(f'\nGet : Fact Summary...')
    chk_result_df = pd.DataFrame.from_records(rows, columns=[x[0] for x in tgt_cur.description])
    print(f'\n   -> chk_result_df : {chk_result_df.shape[0]} rows, {chk_result_df.shape[1]} columns') 
    
    # Display
    tmp_result_df = chk_result_df.copy()
    # tmp_result_df = tmp_result_df.replace(np.nan, None)
    # tmp_result_df.iloc[:, 4:18] = tmp_result_df.iloc[:, 4:18].fillna(0)
    mod_col_list = tmp_result_df.iloc[:, 4:18].columns.tolist()
    for col in mod_col_list:
        tmp_result_df[col] = tmp_result_df[col].apply(lambda x: format(x, ',.2f') if re.search('%', col) else format(x, ',.0f'))
        
    tgt_cur.close()


except oracledb.DatabaseError as e:
    print(f'\nError with Oracle : {e}')


finally:
    tgt_conn.close()

Get : Fact Summary...

   -> chk_result_df : 152 rows, 20 columns

In [19]:
''' Group by '''

agg_df = chk_result_df.groupby(['REMARK', 'TM_KEY_MTH', 'CNT_METRIC']).agg({'AREA_TYPE': 'count', 'ROW_CNT': 'sum', 'LOAD_DATE': 'max'}).sort_values(by=['TM_KEY_MTH']).reset_index()
agg_df

,REMARK,TM_KEY_MTH,CNT_METRIC,AREA_TYPE,ROW_CNT,LOAD_DATE
0,Version as of May26,202501,10,8,11710,2026-09-02 11:48:02.537400
1,Version as of May26,202502,10,8,11710,2026-09-02 11:48:02.537400
2,Version as of May26,202503,10,8,11720,2026-09-02 11:48:02.537400
3,Version as of May26,202504,10,8,11780,2026-09-02 11:48:02.537400
4,Version as of May26,202505,10,8,11780,2026-09-02 11:48:02.537400
5,Version as of May26,202506,10,8,11720,2026-09-02 11:48:02.537400
6,Version as of May26,202507,10,8,11720,2026-09-02 11:48:02.537400
7,Version as of May26,202508,10,8,11720,2026-09-02 11:48:02.537400
8,Version as of May26,202509,10,8,11720,2026-09-02 11:48:02.537400
9,Version as of May26,202510,10,8,11720,2026-09-02 11:48:02.537400
10,Version as of May26,202511,10,8,11720,2026-09-02 11:48:02.537400
11,Version as of May26,202512,10,8,11720,2026-09-02 11:48:02.537400
12,Version as of May26,202601,10,8,11720,2026-09-02 11:48:02.537400
13,Version as of May26,202602,10,8,11720,2026-09-02 11:48:02.537400
14,Version as of May26,202603,10,8,11730,2026-09-02 11:48:02.537400
15,Version as of May26,202604,10,8,11730,2026-09-02 11:48:02.537400
16,Version as of May26,202605,10,8,11730,2026-09-02 11:48:02.537400
17,Version as of May26,202606,10,8,11730,2026-09-02 11:48:02.537400
18,Version as of May26,202607,10,8,11730,2026-09-02 11:48:02.537400

In [22]:
''' Reconcile '''

# Filter
max_mth = chk_result_df['TM_KEY_MTH'].max()
# rec_df = tmp_result_df.loc[tmp_result_df['TM_KEY_MTH']==max_mth]
rec_df = tmp_result_df.loc[tmp_result_df['AREA_TYPE']=='P']
rec_df = rec_df.loc[rec_df['TM_KEY_MTH']>=202501]
# rec_df = rec_df.loc[rec_df['TM_KEY_MTH']>=202601]
rec_df = rec_df.sort_values(by=['TM_KEY_MTH']).reset_index(drop=True)

rec_df#.tail(3)

,TM_KEY_MTH,AREA_NO,AREA_TYPE,REMARK,TOTAL,TOL,AIS & 3BB,NT,3BB,AIS,% TOTAL,% TOL,% AIS & 3BB,% NT,% 3BB,% AIS,CNT_METRIC,CNT_AREA,ROW_CNT,LOAD_DATE
0,202501,1,P,Version as of May26,"9,975,571","3,141,715","5,033,857","1,800,000","2,013,934","3,019,922",100.00,31.49,50.46,18.04,20.19,30.27,10,1,10,2026-09-02 11:48:02.537400
1,202502,1,P,Version as of May26,"10,036,546","3,149,791","5,086,755","1,800,000","1,936,553","3,150,202",100.00,31.38,50.68,17.93,19.30,31.39,10,1,10,2026-09-02 11:48:02.537400
2,202503,1,P,Version as of May26,"10,014,545","3,162,839","5,051,706","1,800,000","1,911,414","3,140,292",100.00,31.58,50.44,17.97,19.09,31.36,10,1,10,2026-09-02 11:48:02.537400
3,202504,1,P,Version as of May26,"10,029,503","3,168,577","5,060,926","1,800,000","1,917,959","3,142,967",100.00,31.59,50.46,17.95,19.12,31.34,10,1,10,2026-09-02 11:48:02.537400
4,202505,1,P,Version as of May26,"10,061,670","3,175,523","5,086,147","1,800,000","1,905,794","3,180,353",100.00,31.56,50.55,17.89,18.94,31.61,10,1,10,2026-09-02 11:48:02.537400
5,202506,1,P,Version as of May26,"10,100,306","3,179,240","5,121,066","1,800,000","1,946,656","3,174,410",100.00,31.48,50.70,17.82,19.27,31.43,10,1,10,2026-09-02 11:48:02.537400
6,202507,1,P,Version as of May26,"10,127,955","3,180,059","5,147,897","1,800,000","1,962,306","3,185,590",100.00,31.40,50.83,17.77,19.38,31.45,10,1,10,2026-09-02 11:48:02.537400
7,202508,1,P,Version as of May26,"10,093,027","3,184,666","5,108,362","1,800,000","1,929,013","3,179,348",100.00,31.55,50.61,17.83,19.11,31.50,10,1,10,2026-09-02 11:48:02.537400
8,202509,1,P,Version as of May26,"10,118,919","3,191,958","5,126,961","1,800,000","1,924,224","3,202,737",100.00,31.54,50.67,17.79,19.02,31.65,10,1,10,2026-09-02 11:48:02.537400
9,202510,1,P,Version as of May26,"10,137,011","3,204,174","5,132,836","1,800,000","1,898,184","3,234,653",100.00,31.61,50.63,17.76,18.73,31.91,10,1,10,2026-09-02 11:48:02.537400
10,202511,1,P,Version as of May26,"10,171,107","3,213,000","5,158,107","1,800,000","1,787,757","3,370,350",100.00,31.59,50.71,17.70,17.58,33.14,10,1,10,2026-09-02 11:48:02.537400
11,202512,1,P,Version as of May26,"10,265,341","3,226,093","5,239,248","1,800,000","962,803","4,276,445",100.00,31.43,51.04,17.53,9.38,41.66,10,1,10,2026-09-02 11:48:02.537400
12,202601,1,P,Version as of May26,"10,315,469","3,237,440","5,278,029","1,800,000","925,649","4,352,380",100.00,31.38,51.17,17.45,8.97,42.19,10,1,10,2026-09-02 11:48:02.537400
13,202602,1,P,Version as of May26,"10,335,449","3,248,955","5,286,494","1,800,000","917,946","4,368,548",100.00,31.44,51.15,17.42,8.88,42.27,10,1,10,2026-09-02 11:48:02.537400
14,202603,1,P,Version as of May26,"10,358,269","3,263,352","5,294,917","1,800,000","878,448","4,416,469",100.00,31.50,51.12,17.38,8.48,42.64,10,1,10,2026-09-02 11:48:02.537400
15,202604,1,P,Version as of May26,"10,396,045","3,272,920","5,323,124","1,800,000","831,616","4,491,509",100.00,31.48,51.20,17.31,8.00,43.20,10,1,10,2026-09-02 11:48:02.537400
16,202605,1,P,Version as of May26,"10,431,910","3,280,553","5,351,357","1,800,000","825,107","4,526,250",100.00,31.45,51.30,17.25,7.91,43.39,10,1,10,2026-09-02 11:48:02.537400
17,202606,1,P,Version as of May26,"10,466,719","3,291,284","5,375,434","1,800,000","870,612","4,504,823",100.00,31.45,51.36,17.20,8.32,43.04,10,1,10,2026-09-02 11:48:02.537400
18,202607,1,P,Version as of May26,"10,484,070","3,305,671","5,378,399","1,800,000","866,388","4,512,011",100.00,31.53,51.30,17.17,8.26,43.04,10,1,10,2026-09-02 11:48:02.537400