# * ETL-Actual MKS : Broadband
    (P, Z, G, H, HH, CCAA) level

In [1]:
import configparser
import datetime as dt
import pandas as pd
import numpy as np
import oracledb
import re
import FN_Actual_MKS_Broadband as fn

config = configparser.ConfigParser()
config.read('../../../my_config.ini')
config.sections()

TDMDBPR_user = config['TDMDBPR']['username']
TDMDBPR_pwd = config['TDMDBPR']['password']
TDMDBPR_db = config['TDMDBPR']['db']
TDMDBPR_host = config['TDMDBPR']['host']
TDMDBPR_port = config['TDMDBPR']['port']

AKPIPRD_user = config['AKPIPRD']['username']
AKPIPRD_pwd = config['AKPIPRD']['password']
AKPIPRD_db = config['AKPIPRD']['db']
AKPIPRD_host = config['AKPIPRD']['host']
AKPIPRD_port = config['AKPIPRD']['port']

curr_dt = dt.datetime.now().date()
next_week_dt = curr_dt + dt.timedelta(days=7)
str_curr_dt = curr_dt.strftime('%Y%m%d')
str_next_week_dt = next_week_dt.strftime('%Y%m%d')
yyyymm_curr = curr_dt.strftime('%Y%m')
yyyymm_next_week = next_week_dt.strftime('%Y%m')

## Latest Source Summary

In [3]:
# Connect : TDMDBPR
src_dsn = f'{TDMDBPR_user}/{TDMDBPR_pwd}@{TDMDBPR_host}:{TDMDBPR_port}/{TDMDBPR_db}'
src_conn = oracledb.connect(src_dsn)
src_cur = src_conn.cursor()


try:
    # Get : Actual Summary from "FCT_BB_SHAREV4_ISP_SUBS"
    src_cur.execute("""
        SELECT *
        FROM (
            SELECT TM_KEY_MTH
                , CASE WHEN AREA_TYPE = 'TH' THEN 'P' ELSE AREA_TYPE END AREA_TYPE
                , SUM(COALESCE(TOL,0) + COALESCE(AISBBB,0) + COALESCE(NT,0)) TOTAL
                , SUM(TOL) TOL
                , SUM(AISBBB) AISBBB
                , SUM(NT) NT
                , SUM(BBB) "3BB"
                , SUM(AIS) AIS
            FROM CORPNSBOX.FCT_BB_SHAREV4_ISP_SUBS A
            WHERE TM_KEY_MTH >= 202601
            --AND TM_KEY_MTH <= 202512
            AND VER = 'FINAL'
            AND (AREA_TYPE = 'TH' 
                OR (AREA_TYPE = 'CCAA' AND EXISTS (SELECT 1 FROM CDSAPPO.DIM_MOOC_AREA O WHERE O.TEAM_CODE <> 'ไม่ระบุ' AND O.REMARK <> 'Dummy' AND SUBSTR(O.CCAATT,1,4) = A.AREA_CD)))
            GROUP BY TM_KEY_MTH, AREA_TYPE
        ) TMP
        WHERE TOL > 0 AND AISBBB > 0 AND NT > 0
        AND AREA_TYPE = 'P'
        ORDER BY 1,2
    """)
    rows = src_cur.fetchall()
    print(f'\nCurrent Source Summary...')
    chk_src_df = pd.DataFrame.from_records(rows, columns=[x[0] for x in src_cur.description])

    # Get : MAX(TM_KEY_MTH)
    v_mth_end_src = chk_src_df['TM_KEY_MTH'].max().astype(float)
    print(f'\nv_mth_end_src: {v_mth_end_src}')
    # print(f'\nv_mth_end_src: {v_mth_end_src[0]}')
    
    src_cur.close()


except oracledb.DatabaseError as e:
    print(f'\nError with Oracle : {e}')


finally:
    src_conn.close()

Current Source Summary...

v_mth_end_src: 202608.0

In [17]:
''' Source Summary '''

tmp_src_df = chk_src_df.copy()
mod_col_list = tmp_src_df.iloc[:, 2:].columns.tolist()
for col in mod_col_list:
    tmp_src_df[col] = tmp_src_df[col].apply(lambda x: format(x, ',.0f'))
# print(f'\n{tmp_src_df}')

tmp_src_df

,TM_KEY_MTH,AREA_TYPE,TOTAL,TOL,AISBBB,NT,3BB,AIS
0,202601,P,"10,315,469","3,237,440","5,278,029","1,800,000","925,649","4,352,380"
1,202602,P,"10,335,449","3,248,955","5,286,494","1,800,000","917,946","4,368,548"
2,202603,P,"10,358,269","3,263,352","5,294,917","1,800,000","878,448","4,416,469"
3,202604,P,"10,396,044","3,272,920","5,323,124","1,800,000","831,616","4,491,509"
4,202605,P,"10,431,910","3,280,553","5,351,357","1,800,000","825,107","4,526,250"
5,202606,P,"10,466,718","3,291,284","5,375,434","1,800,000","870,612","4,504,823"
6,202607,P,"10,484,070","3,305,671","5,378,399","1,800,000","866,388","4,512,011"
7,202608,P,"10,470,558","3,317,517","5,353,041","1,800,000","948,462","4,404,578"

## Latest Fact Summary

In [5]:
# Connect : AKPIPRD
tgt_dsn = f'{AKPIPRD_user}/{AKPIPRD_pwd}@{AKPIPRD_host}:{AKPIPRD_port}/{AKPIPRD_db}'
tgt_conn = oracledb.connect(tgt_dsn)
tgt_cur = tgt_conn.cursor()


try:
    # Get : Actual Summary from "FCT_BROADBAND_MKS"
    tgt_cur.execute("""
        SELECT TM_KEY_MTH, AREA_TYPE 
            , SUM(CASE WHEN METRIC_CD IN ('VIN00081', 'VIN00082', 'VIN00083', 'VIN00084') THEN SUBS_VALUE END) AS TOTAL
            , SUM(CASE WHEN METRIC_CD = 'VIN00081' THEN SUBS_VALUE END) AS TOL
            , SUM(CASE WHEN METRIC_CD = 'VIN00080' THEN SUBS_VALUE END) AS AISBBB
            , SUM(CASE WHEN METRIC_CD = 'VIN00084' THEN SUBS_VALUE END) AS NT
            , SUM(CASE WHEN METRIC_CD = 'VIN00082' THEN SUBS_VALUE END) "3BB"
            , SUM(CASE WHEN METRIC_CD = 'VIN00083' THEN SUBS_VALUE END) AIS
            --, MAX(LOAD_DATE) LOAD_DATE
        FROM AUTOKPI.FCT_BROADBAND_MKS 
        WHERE TM_KEY_MTH >= 202601 --AND TM_KEY_MTH <= 202404
        AND TM_KEY_DAY LIKE '%01'
        AND AREA_TYPE = 'P'
        GROUP BY TM_KEY_MTH, AREA_TYPE 
        ORDER BY 1
    """)
    rows = tgt_cur.fetchall()
    print(f'\nCurrent Fact Summary...')
    chk_tgt_df = pd.DataFrame.from_records(rows, columns=[x[0] for x in tgt_cur.description])

    # Get : MAX(TM_KEY_MTH)
    v_mth_end_fct = chk_tgt_df['TM_KEY_MTH'].max().astype(float)
    print(f'\nv_mth_end_fct: {v_mth_end_fct}')

    # tgt_cur.execute("SELECT MAX(TM_KEY_MTH) FROM AUTOKPI.FCT_BROADBAND_MKS NOLOCK")
    # max_mth_fct = tgt_cur.fetchone()
    # print(f'\nv_max_mth_fct: {max_mth_fct[0]}')
    
    tgt_cur.close()


except oracledb.DatabaseError as e:
    print(f'\nError with Oracle : {e}')


finally:
    tgt_conn.close()

Current Fact Summary...

v_mth_end_fct: 202608.0

In [6]:
''' Silver Summary '''

tmp_tgt_df = chk_tgt_df.copy()
mod_col_list = tmp_tgt_df.iloc[:, 2:].columns.tolist()
for col in mod_col_list:
    tmp_tgt_df[col] = tmp_tgt_df[col].apply(lambda x: format(x, ',.0f'))
# print(f'\n{tmp_tgt_df}')

tmp_tgt_df

,TM_KEY_MTH,AREA_TYPE,TOTAL,TOL,AISBBB,NT,3BB,AIS
0,202601,P,"10,315,469","3,237,440","5,278,029","1,800,000","925,649","4,352,380"
1,202602,P,"10,335,449","3,248,955","5,286,494","1,800,000","917,946","4,368,548"
2,202603,P,"10,358,269","3,263,352","5,294,917","1,800,000","878,448","4,416,469"
3,202604,P,"10,396,045","3,272,920","5,323,124","1,800,000","831,616","4,491,509"
4,202605,P,"10,431,910","3,280,553","5,351,357","1,800,000","825,107","4,526,250"
5,202606,P,"10,466,719","3,291,284","5,375,434","1,800,000","870,612","4,504,823"
6,202607,P,"10,484,070","3,305,671","5,378,399","1,800,000","866,388","4,512,011"
7,202608,P,"10,470,557","3,317,517","5,353,041","1,800,000","948,462","4,404,578"

## Check Diff Summary

In [ ]:
# ''' Temp '''

# chk_diff_df = chk_src_df.iloc[-1].compare(chk_tgt_df.iloc[-1])
# chk_diff_df['diff'] = chk_diff_df['self'] - chk_diff_df['other']
# mod_col_list = chk_diff_df.columns.tolist()
# for col in mod_col_list:
#     chk_diff_df[col] = chk_diff_df[col].apply(lambda x: format(x, ',.0f'))

# chk_diff_df

In [7]:
''' Compare Latest Actual '''

latest_src_actual = chk_src_df.loc[chk_src_df['TM_KEY_MTH']==v_mth_end_src]
# latest_src_actual

# latest_fct_actual = chk_tgt_df.loc[chk_tgt_df['TM_KEY_MTH']==v_mth_end_src]
latest_fct_actual = chk_tgt_df.loc[chk_tgt_df['TM_KEY_MTH']==chk_tgt_df['TM_KEY_MTH'].max()]
# latest_fct_actual

chk_diff_latest_actual = latest_src_actual.iloc[-1].compare(latest_fct_actual.iloc[-1])
chk_diff_latest_actual['diff'] = chk_diff_latest_actual['self'] - chk_diff_latest_actual['other']
mod_col_list = chk_diff_latest_actual.columns.tolist()
for col in mod_col_list:
    chk_diff_latest_actual[col] = chk_diff_latest_actual[col].apply(lambda x: format(x, ',.0f'))

chk_diff_latest_actual

             self       other diff
TOTAL  10,470,558  10,470,557    1

## ETL Process...

### DB source to DB Target
    Delete -> Insert

    Source : CORPNSBOX.FCT_BB_SHARE_SUBS_CCAATT
             CDSAPPO.DIM_MOOC_AREA
             CDSAPPO.DIM_TIME
    
    Target : AUTOKPI.FCT_BROADBAND_MKS

### Input Parameter

In [21]:
''' Manual Config '''
# v_update_flag = 'N'
v_target_schema = 'AUTOKPI'
v_target_table = 'FCT_BROADBAND_MKS'
v_sql_update_fact = 'Update-FCT_BROADBAND_MKS.sql'
v_sql_mockup_fact = 'Mock-FCT_BROADBAND_MKS.sql'
v_sql_initial_fact = 'Initial-FCT_BROADBAND_MKS.sql'

''' Auto Config '''
v_update_flag = 'Y' if chk_diff_latest_actual.size > 0 else 'N'
# v_max_mth_fct = max_mth_fct[0]
v_mth_end_fct_year = pd.to_datetime(v_mth_end_fct, format='%Y%m').year
v_mth_end_fct_month = pd.to_datetime(v_mth_end_fct, format='%Y%m').month
# v_prev_mth_fct = v_mth_end_fct-1 if v_mth_end_fct_month != 1 else float(str(v_mth_end_fct_year-1)+str(12))

''' Show Auto Config '''
print(f'\nyyyymm_next_week: {yyyymm_next_week}')
print(f'\nv_update_flag: {v_update_flag}')
print(f'v_mth_end_src: {v_mth_end_src}')
print(f'v_mth_end_fct: {v_mth_end_fct}')
# print(f'v_max_mth_fct: {v_max_mth_fct}')
# print(f'v_prev_mth_fct: {v_prev_mth_fct}')

yyyymm_next_week: 202609

v_update_flag: Y
v_mth_end_src: 202608.0
v_mth_end_fct: 202607.0

#### Incremental

In [22]:
''' Auto Process '''

job_start_datetime = dt.datetime.now().strftime('%Y-%m-%d, %H:%M:%S')
print(f'\nJob Start... {job_start_datetime}')

# Process flow
if v_update_flag == 'Y':
    print(f'\n*** Source update current month Fact ***')
    fn.src_update_to_fact(v_mth_end_src, v_target_schema, v_target_table, v_sql_update_fact)

elif v_update_flag == 'N':
    print(f'\n*** Not update ***')
        
print(f'\nJob Done !!!')

Job Start... 2026-09-11, 14:56:19

*** Source update current month Fact ***

Param input...

   -> mth_end_src: 202608.0
   -> target_schema: AUTOKPI
   -> target_table: FCT_BROADBAND_MKS
   -> sql_update_fact: Update-FCT_BROADBAND_MKS.sql
   -> v_query_param: {'mth_end_src': 202608.0}

TDMDBPR : Connected

AKPIPRD : Connected

Processing...

Create Dataframe...

   -> src_df : 363630 rows, 17 columns

   -> DELETE : "FCT_BROADBAND_MKS" : Done !

   -> INSERT : "FCT_BROADBAND_MKS" : Done !

TDMDBPR : Disconnected

AKPIPRD : Disconnected

Job Done !!!

#### Initial

In [17]:
# ''' Initial Process '''

# v_initial_mth_start = 202501
# v_initial_mth_end = 202607

# job_start_datetime = dt.datetime.now().strftime('%Y-%m-%d, %H:%M:%S')
# print(f'\nJob Start... {job_start_datetime}')

# print(f'\n*** Re-run initial data to Fact ***')
# fn.src_initial_to_fact(v_initial_mth_start, v_initial_mth_end, v_target_schema, v_target_table, v_sql_initial_fact)

# print(f'\nJob Done !!!')

Job Start... 2026-09-02, 11:34:24

*** Re-run initial data to Fact ***

Param input...

   -> initial_mth_start: 202501
   -> initial_mth_end: 202607
   -> target_schema: AUTOKPI
   -> target_table: FCT_BROADBAND_MKS
   -> sql_initial_fact: Initial-FCT_BROADBAND_MKS.sql
   -> v_query_param: {'initial_mth_start': 202501, 'initial_mth_end': 202607}

TDMDBPR : Connected

AKPIPRD : Connected

Processing...

Create Dataframe...

   -> src_df : 6767040 rows, 17 columns

   -> DELETE : "FCT_BROADBAND_MKS" : Done !

   -> INSERT : "FCT_BROADBAND_MKS" : Done !

TDMDBPR : Disconnected

AKPIPRD : Disconnected

Job Done !!!

## Check Result : "FCT_BROADBAND_MKS"

In [23]:
''' Create Result DataFrame '''

# Connect : AKPIPRD
tgt_dsn = f'{AKPIPRD_user}/{AKPIPRD_pwd}@{AKPIPRD_host}:{AKPIPRD_port}/{AKPIPRD_db}'
tgt_conn = oracledb.connect(tgt_dsn)
tgt_cur = tgt_conn.cursor()


try:
    # Get : Result Data Summary
    tgt_cur.execute("""
        SELECT TM_KEY_MTH, AREA_NO, AREA_TYPE, COALESCE(REMARK, 'Actual') AS REMARK
            -->> Subs
            , SUM(CASE WHEN METRIC_CD IN ('VIN00086', 'VIN00087', 'VIN00088', 'VIN00089') THEN METRIC_VALUE END) AS TOTAL
            , SUM(CASE WHEN METRIC_CD = 'VIN00086' THEN METRIC_VALUE END) AS TOL
            , SUM(CASE WHEN METRIC_CD = 'VIN00085' THEN METRIC_VALUE END) AS "AIS & 3BB"
            , SUM(CASE WHEN METRIC_CD = 'VIN00089' THEN METRIC_VALUE END) AS NT
            , SUM(CASE WHEN METRIC_CD = 'VIN00087' THEN METRIC_VALUE END) AS "3BB"
            , SUM(CASE WHEN METRIC_CD = 'VIN00088' THEN METRIC_VALUE END) AS AIS
            -->> % MKS
            , SUM(CASE WHEN AREA_TYPE = 'P' AND METRIC_CD IN ('VIN00081', 'VIN00082', 'VIN00083', 'VIN00084') THEN METRIC_VALUE END) AS "% TOTAL"
            , SUM(CASE WHEN AREA_TYPE = 'P' AND METRIC_CD = 'VIN00081' THEN METRIC_VALUE END) AS "% TOL"
            , SUM(CASE WHEN AREA_TYPE = 'P' AND METRIC_CD = 'VIN00080' THEN METRIC_VALUE END) AS "% AIS & 3BB"
            , SUM(CASE WHEN AREA_TYPE = 'P' AND METRIC_CD = 'VIN00084' THEN METRIC_VALUE END) AS "% NT"
            , SUM(CASE WHEN AREA_TYPE = 'P' AND METRIC_CD = 'VIN00082' THEN METRIC_VALUE END) AS "% 3BB"
            , SUM(CASE WHEN AREA_TYPE = 'P' AND METRIC_CD = 'VIN00083' THEN METRIC_VALUE END) AS "% AIS"
            -->> Count
            , COUNT(DISTINCT METRIC_CD) AS CNT_METRIC
            , COUNT(DISTINCT AREA_CD) AS CNT_AREA
            , COUNT(1) AS ROW_CNT
            , MAX(LOAD_DATE) AS LOAD_DATE
        FROM AUTOKPI.FCT_BROADBAND_MKS 
        WHERE TM_KEY_DAY >= 20260101
        AND TM_KEY_DAY LIKE '%01'
        GROUP BY TM_KEY_MTH, AREA_NO, AREA_TYPE, REMARK
        --ORDER BY 1,2
    """)
    rows = tgt_cur.fetchall()
    print(f'\nGet : Fact Summary...')
    chk_result_df = pd.DataFrame.from_records(rows, columns=[x[0] for x in tgt_cur.description])
    print(f'\n   -> chk_result_df : {chk_result_df.shape[0]} rows, {chk_result_df.shape[1]} columns') 
    
    # Display
    tmp_result_df = chk_result_df.copy()
    # tmp_result_df = tmp_result_df.replace(np.nan, None)
    # tmp_result_df.iloc[:, 4:18] = tmp_result_df.iloc[:, 4:18].fillna(0)
    mod_col_list = tmp_result_df.iloc[:, 4:18].columns.tolist()
    for col in mod_col_list:
        tmp_result_df[col] = tmp_result_df[col].apply(lambda x: format(x, ',.2f') if re.search('%', col) else format(x, ',.0f'))
        
    tgt_cur.close()


except oracledb.DatabaseError as e:
    print(f'\nError with Oracle : {e}')


finally:
    tgt_conn.close()

Get : Fact Summary...

   -> chk_result_df : 64 rows, 20 columns

In [24]:
''' Group by '''

agg_df = chk_result_df.groupby(['REMARK', 'TM_KEY_MTH', 'CNT_METRIC']).agg({'AREA_TYPE': 'count', 'ROW_CNT': 'sum', 'LOAD_DATE': 'max'}).sort_values(by=['TM_KEY_MTH']).reset_index()
agg_df

,REMARK,TM_KEY_MTH,CNT_METRIC,AREA_TYPE,ROW_CNT,LOAD_DATE
0,Version as of May26,202601,10,8,11720,2026-09-02 11:48:02.537400
1,Version as of May26,202602,10,8,11720,2026-09-02 11:48:02.537400
2,Version as of May26,202603,10,8,11730,2026-09-02 11:48:02.537400
3,Version as of May26,202604,10,8,11730,2026-09-02 11:48:02.537400
4,Version as of May26,202605,10,8,11730,2026-09-02 11:48:02.537400
5,Version as of May26,202606,10,8,11730,2026-09-02 11:48:02.537400
6,Version as of May26,202607,10,8,11730,2026-09-02 11:48:02.537400
7,Version as of May26,202608,10,8,11730,2026-09-11 14:56:52.609880

In [25]:
''' Reconcile '''

# Filter
max_mth = chk_result_df['TM_KEY_MTH'].max()
# rec_df = tmp_result_df.loc[tmp_result_df['TM_KEY_MTH']==max_mth]
rec_df = tmp_result_df.loc[tmp_result_df['AREA_TYPE']=='P']
rec_df = rec_df.loc[rec_df['TM_KEY_MTH']>=202501]
# rec_df = rec_df.loc[rec_df['TM_KEY_MTH']>=202601]
rec_df = rec_df.sort_values(by=['TM_KEY_MTH']).reset_index(drop=True)

rec_df#.tail(3)

,TM_KEY_MTH,AREA_NO,AREA_TYPE,REMARK,TOTAL,TOL,AIS & 3BB,NT,3BB,AIS,% TOTAL,% TOL,% AIS & 3BB,% NT,% 3BB,% AIS,CNT_METRIC,CNT_AREA,ROW_CNT,LOAD_DATE
0,202601,1,P,Version as of May26,"10,315,469","3,237,440","5,278,029","1,800,000","925,649","4,352,380",100.00,31.38,51.17,17.45,8.97,42.19,10,1,10,2026-09-02 11:48:02.537400
1,202602,1,P,Version as of May26,"10,335,449","3,248,955","5,286,494","1,800,000","917,946","4,368,548",100.00,31.44,51.15,17.42,8.88,42.27,10,1,10,2026-09-02 11:48:02.537400
2,202603,1,P,Version as of May26,"10,358,269","3,263,352","5,294,917","1,800,000","878,448","4,416,469",100.00,31.50,51.12,17.38,8.48,42.64,10,1,10,2026-09-02 11:48:02.537400
3,202604,1,P,Version as of May26,"10,396,045","3,272,920","5,323,124","1,800,000","831,616","4,491,509",100.00,31.48,51.20,17.31,8.00,43.20,10,1,10,2026-09-02 11:48:02.537400
4,202605,1,P,Version as of May26,"10,431,910","3,280,553","5,351,357","1,800,000","825,107","4,526,250",100.00,31.45,51.30,17.25,7.91,43.39,10,1,10,2026-09-02 11:48:02.537400
5,202606,1,P,Version as of May26,"10,466,719","3,291,284","5,375,434","1,800,000","870,612","4,504,823",100.00,31.45,51.36,17.20,8.32,43.04,10,1,10,2026-09-02 11:48:02.537400
6,202607,1,P,Version as of May26,"10,484,070","3,305,671","5,378,399","1,800,000","866,388","4,512,011",100.00,31.53,51.30,17.17,8.26,43.04,10,1,10,2026-09-02 11:48:02.537400
7,202608,1,P,Version as of May26,"10,470,557","3,317,517","5,353,041","1,800,000","948,462","4,404,578",100.00,31.68,51.12,17.19,9.06,42.07,10,1,10,2026-09-11 14:56:52.609880